services:
  ds-python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: ds-python
    expose: 
      - 8888
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ../:/app
      